dataset: "deepglobe_land"
fold: 0
in_channels: 3
num_classes: 6
scale_min: 0.5
scale_max: 2.0
crop_size: [512, 512]
ignore_index: 6
reduce_zero_label: False
image_prefix: null
image_suffix: "sat.jpg"
label_prefix: null
label_suffix: "label.png"
